config/routes.rb
Rails.application.routes.draw do
  resources :dislikes, only: [:create, :index]
  resources :likes, only: [:create, :index]
  resources :users

  resources :conversations do
    resources :messages
  end

  root 'application#index'

  get '/users/:id/random', to: 'users#random'
  get '/users/:id/matches', to: 'users#matches'
  get '/users/:id/profile', to: 'users#profile'
  get '/users/:id/no_matches', to: 'users#no_matches'
  get '/users/:id/new_match/:likee_id', to: 'users#new_match'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  get '/users/:id/delete', to: 'users#destroy'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  has_many :inverse_likes, class_name: "Like", foreign_key: "likee_id", dependent: :destroy
  has_many :inverse_dislikes, class_name: "Dislike", foreign_key: "dislikee_id", dependent: :destroy

  # makes sure all fields are filled
  validates :username, :email, :location, :pet_name, :pet_age, :pet_bio, :pet_pic, presence: true

  # username & email must be unique & are not case sensitive
  validates :username, :email, uniqueness: true, case_sensitive: false

  # length validations
  validates :username, length: {in: 5..20}
  validates :pet_bio, length: {in: 10..300}

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  # no numbers; need to add other validations!
  validates :location, numericality: false

  has_many_attached :pet_pic


  has_secure_password

  # trying to validate that pic is an image, doesn't work:
  # validates :pet_pic, { with: "image/jpg", "image/jpeg", "image/png", "image/gif"}

  # HELPER METHODS

  # returns array - all users that haven't been liked or disliked by user
  def users_not_seen_yet
    arr = []
    arr << self.who_user_likes << self.who_user_dislikes << self.id
    arr = arr.flatten
    User.where.not(id: arr)
  end

  def who_user_likes
    self.likes.map do |like|
      like.likee_id
    end
  end

  def who_user_dislikes
    self.dislikes.map do |dislike|
      dislike.dislikee_id
    end
  end

  def who_likes_user
    self.inverse_likes.map do |inv_like|
      inv_like.user_id
    end
  end

  def get_match_ids
    self.who_user_likes & self.who_likes_user
  end

  def get_matches
    match_ids = self.get_match_ids
    match_ids.map do |match_id|
      User.find_by(id: match_id)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :random,
    :likes, :dislikes, :matches, :profile, :new_match, :no_matches]
  before_action :already_logged_in, only: [:new, :create]
  skip_before_action :authenticate_user, only: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to "/users/#{@user.id}/profile"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to "/users/#{@user.id}/profile"
    else
      render :edit
    end
  end

  def random
    # if there are still users to show, create new dis/like
    # else send them to no matches page
    if @random_user = @user.users_not_seen_yet.sample
      @like = Like.new
      @dislike = Dislike.new
    else
      redirect_to "/users/#{@user.id}/no_matches"
    end
  end

  def new_match
    @likee = User.find(params[:likee_id])
  end

  def destroy
    @user.delete
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email, :location, :pet_name, :pet_age, :pet_bio, pet_pic: [])
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="space">
  <header class="text-center">
    <div class="masthead-content">
      <div class="container">

        <!-- SHOWS ERRORS -->
        <% if @user.errors.any? %>
          <div class="text-danger">
            <%= pluralize(@user.errors.count, "error") %> prohibited these updates from being saved:<br>
            <% @user.errors.full_messages.each do |msg| %>
              <%= msg %><br>
            <% end %>
          </div><br>
        <% end %>

        <!-- NEW USER FORM -->

        <h1>Edit your Profile</h1><br>

        <%= form_for @user do |f| %>
          <h4 class="masthead-subheading mb-0"><%= f.label :username %></h4>
            <%= f.text_field :username %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :password %></h4>
            <%= f.password_field :password %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :password_confirmation %></h4>
            <%= f.password_field :password_confirmation %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :email %></h4>
            <%= f.text_field :email %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :location %></h4>
            <%= f.text_field :location %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :pet_pic %></h4>
            <%= f.file_field :pet_pic, multiple: true %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :pet_name %></h4>
            <%= f.text_field :pet_name %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :pet_age %></h4>
            <%= f.number_field :pet_age %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :pet_bio %></h4>
            <%= f.text_area :pet_bio %><br>

          <%= f.submit "Update Profile", class: "btn btn-primary btn-lg rounded-pill mt-5" %><br>
          <%= link_to "Delete Profile", "/users/#{@user.id}/delete", class: "btn btn-primary btn-lg rounded-pill mt-5" %>
        <% end %>

      </div>
    </div>
  </header>
  <footer class="space"></footer>
</div>

app/views/users/matches.html.erb
<section>
  <div class="space">
    <h1 align="center" style="font-size:100px; margin-bottom:50px;"><%= @user.pet_name %>'s Matches</h1>
    <div class="container">
      <% @user.get_matches.each do |match| %>
        <% match.pet_pic.each do |pic| %>
          <div class="row" style="margin-bottom:80px;">
            <div class="col-md-6">
              <img class="img-fluid rounded-circle" src="<%= url_for(pic.variant(resize: "500x500")) %>" alt="">
            </div>
            <div class="col-md-6">
              <h2 class="display-4" style="line-height:6em"><%= link_to "View #{match.pet_name}'s Profile", user_path(match), class:"btn btn-primary btn-xl rounded-pill mt-5" %></h2>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<div class="space">
  <header class="text-center">
    <div class="masthead-content">
      <div class="container">

        <!-- SHOWS ERRORS -->
        <% if @user.errors.any? %>
          <div class="text-danger">
            <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:<br>
            <% @user.errors.full_messages.each do |msg| %>
              <%= msg %><br>
            <% end %>
          </div><br>
        <% end %>

        <!-- NEW USER FORM -->

        <h1>Create a Profile</h1><br>

        <%= form_for @user do |f| %>
          <h4 class="masthead-subheading mb-0"><%= f.label :username, "Create a username:" %></h4>
            <%= f.text_field :username %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :password, "Create a password:" %></h4>
            <%= f.password_field :password %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :password_confirmation, "Confirm password:" %></h4>
            <%= f.password_field :password_confirmation %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :email, "Email:" %></h4>
            <%= f.text_field :email %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :location, "Location:" %></h4>
            <%= f.text_field :location %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :pet_pic, "Upload a picture of your pet:" %></h4>
            <%= f.file_field :pet_pic, multiple: true %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :pet_name, "Your pet's name:" %></h4>
            <%= f.text_field :pet_name %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :pet_age, "Your pet's age:" %></h4>
            <%= f.number_field :pet_age %><br><br>

          <h4 class="masthead-subheading mb-0"><%= f.label :pet_bio, "Write a bio about your pet:" %></h4>
            <%= f.text_area :pet_bio %><br>

          <%= f.submit "Create New User", class: "btn btn-primary btn-xl rounded-pill mt-5" %>

        <% end %>

      </div>
    </div>
  </header>
  <footer class="space"></footer>
</div>

app/views/users/new_match.html.erb
<section>
  <div class="space">
    <h1 class="text-center display-3">It's a match!</h1>
    <div class="container">
      <div class="row align-items-center">
        <!-- SHOW LIKEE PICTURE -->
        <div class="col-lg-6">
          <div class="p-5">
            <% @likee.pet_pic.each do |pic| %>
              <img class="img-fluid rounded-circle" src="<%= url_for(pic.variant(resize: "500x500")) %>">
            <% end %>
          </div>
        </div>
        <!-- SHOW LIKEE INFO -->
        <div class="col-lg-6">
          <div class="p-5">
            <h2 class="display-4"><%= @likee.pet_name %></h2>
            <p>Location: <%= @likee.location %></p>
            <p>Age: <%= @likee.pet_age %></p>
            <p>Bio: <%= @likee.pet_bio %></p>
            <%= link_to "Message #{@likee.pet_name}!", conversations_path(sender_id: @user.id, recipient_id: @likee.id), method:'post', class:"btn btn-primary btn-xl rounded-pill mt-5" %>
            <%= link_to "go back to swiping", "/users/#{@user.id}/random", class:"btn btn-primary btn-xl rounded-pill mt-5" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/no_matches.html.erb
<div class="space">

  <header class="text-center">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0 display-4"">You've seen everyone!</h1>
      </div>
    </div>

  </header>

</div>

app/views/users/profile.html.erb
<section>
  <div class="space">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <% @user.pet_pic.each do |pic| %>
          <img class="img-fluid rounded-circle" src="<%= url_for(pic.variant(resize: "500x500")) %>" alt="">
          <% end %>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4"><%= @user.pet_name %>'s Profile</h2>
          <p>Username: <%= @user.username %></p>
          <p>Email: <%= @user.email %></p>
          <p>Location: <%= @user.location %></p>
          <p>Age: <%= @user.pet_age %></p>
          <p>Bio: <%= @user.pet_bio %></p>
          <p><%= link_to "Edit Profile", "/users/#{@user.id}/edit", class:"btn btn-primary btn-xl rounded-pill mt-5" %></p>
        </div>
      </div>
    </div>
  </div>
  </div>
</section>

app/views/users/random.html.erb
<section>
  <div class="space">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <% @random_user.pet_pic.each do |pic| %>
          <img class="img-fluid rounded-circle" src="<%= url_for(pic.variant(resize: "500x500")) %>" alt="">
          <% end %>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4"><%= @random_user.pet_name %></h2>
          <p>Location: <%= @random_user.location %></p>
          <p>Age: <%= @random_user.pet_age %></p>
          <p>Bio: <%= @random_user.pet_bio %></p>
          <div class="input-group">
            <%= form_for @dislike do |f| %>
            <%= f.hidden_field :user_id, :value => @user.id %>
            <%= f.hidden_field :dislikee_id, :value=> @random_user.id %>
            <%= f.submit "Dislike", class:"btn btn-primary btn-xl rounded-pill mt-5" %>
            <% end %>
            <span class="input-group-addon" style="visibility: hidden">" "</span>
          <%= form_for @like do |f| %>
            <%= f.hidden_field :user_id, :value => @user.id %>
            <%= f.hidden_field :likee_id, :value=> @random_user.id %>
            <%= f.submit "Like", class:"btn btn-primary btn-xl rounded-pill mt-5" %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</section>

app/views/users/show.html.erb
<section>
  <div class="space">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <% @user.pet_pic.each do |pic| %>
          <img class="img-fluid rounded-circle" src="<%= url_for(pic.variant(resize: "500x500")) %>" alt="">
          <% end %>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4"><%= @user.pet_name %></h2>
          <p>Location: <%= @user.location %></p>
          <p>Age: <%= @user.pet_age %></p>
          <p>Bio: <%= @user.pet_bio %></p>
          <% if logged_in? && current_user.id != @user.id %>
          <p><%= link_to "Message #{@user.pet_name}", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post', class:"btn btn-primary btn-xl rounded-pill mt-5" %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  </div>
</section>