config/routes.rb
Rails.application.routes.draw do
  resources :dislikes, only: [:create, :index]
  resources :likes, only: [:create, :index]
  resources :users

  resources :conversations do
    resources :messages
  end

  root 'application#index'

  get '/users/:id/random', to: 'users#random'
  get '/users/:id/matches', to: 'users#matches'
  get '/users/:id/profile', to: 'users#profile'
  get '/users/:id/no_matches', to: 'users#no_matches'
  get '/users/:id/new_match/:likee_id', to: 'users#new_match'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  get '/users/:id/delete', to: 'users#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PetMatchr</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  </head>

  <body>
    <!-- NAVIGATION BAR -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
      <div class="container">

        <% if logged_in? %>
          <a class="navbar-brand" href="<%= "/users/#{current_user.id}/profile" %>">PetMatchr</a>
        <% else %>
          <a class="navbar-brand" href="<%= root_path %>">PetMatchr</a>
        <% end %>

        <ul class="navbar-nav ml-auto">
          <% if request.path_info.include?("login") %>
          <% elsif request.path_info.include?("users/new") %>
          <% elsif logged_in? %>
            <li class="nav-item">
              <a class="nav-link" href="<%= "/users/#{current_user.id}/profile" %>">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= "/users/#{current_user.id}/random" %>">Find Matches</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= "/users/#{current_user.id}/matches" %>">Your Matches</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= conversations_path %>">Conversations</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= logout_path %>">Logout</a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_path %>">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= login_path %>">Login</a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>